[book]
authors = ["KryonLabs"]
language = "en"
multilingual = false
src = "src"
title = "Kryon Documentation"
description = "Build efficient, cross-platform user interfaces"

[preprocessor.links]

[output.html]
additional-css = ["assets/custom.css"]
additional-js = ["assets/kry.js"]
git-repository-url = "https://github.com/kryonlabs/kryon-docs"
edit-url-template = "https://github.com/kryonlabs/kryon-docs/edit/main/src/{path}"

[output.html.search]
enable = true

[output.html.print]
enable = true