# This file defines the GitHub Actions workflow to build and deploy an mdBook site.
# It should be placed in the .github/workflows/ directory of your repository.

name: Deploy mdBook to Netlify

# This workflow runs on any push to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  # The 'deploy' job handles the entire build and deployment process.
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the source code from your repository.
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Install mdBook. This action is a convenient wrapper that
      # handles installing the Rust toolchain and mdBook itself.
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          # You can pin the mdBook version for consistent builds.
          mdbook-version: '0.4.37' 

      # Step 3: Run the 'mdbook build' command.
      # This generates the static HTML files for your book.
      # By default, the output is placed in a directory named 'book'.
      - name: Build the book
        run: mdbook build

      # Step 4: Deploy the generated site to Netlify.
      # This action handles the communication with Netlify's API.
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.1
        with:
          # The directory that contains the built site.
          publish-dir: './book'
          # Tells Netlify this is a production deploy because it's from the main branch.
          production-branch: main
          # A descriptive message for the Netlify deploy log.
          deploy-message: "Deploy from GitHub Actions: ${{ github.event.head_commit.message }}"
        env:
          # These secrets MUST be configured in your GitHub repository's settings.
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1