# .github/workflows/deploy.yml
name: Deploy mdBook to Netlify

on:
  push:
    branches:
      - main # Or whatever your default branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # This action is much cleaner than installing the Rust toolchain manually
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.37' # Pin the version for consistency

      - name: Build the book
        run: mdbook build

      - name: Deploy to Netlify
        # Use the official Netlify Deploy Action for a more stable experience
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: './book'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions: ${{ github.event.head_commit.message }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1